- name: Use docker compose to run all containers
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
      become: true

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./

    - name: Run docker compose up command
      become: true
      docker_compose:
        project_src: .
        state: present
        pull: yes
